| `Session_Welcome_Title -> "Connectez-vous avec RunOrg"
| `Session_Welcome_Head -> "Connectez-vous avec RunOrg"
| `Session_Welcome_Head_Sub -> "Votre passeport RunOrg vous donne accès aux sites privés des groupes dont vous êtes membre."
| `Session_Welcome_Email -> "Adresse email"
| `Session_Welcome_Password -> "Mot de passe"
| `Session_Welcome_Button_Login -> "Connexion"
| `Session_Welcome_Button_Signup -> "Inscription"
