(* © 2013 RunOrg *)

(** The type of a token generated by the template lexer. *)
type token = 
  | Html of string
  | Block of string
  | BeginEcho
  | BeginI18n
  | BeginSub
  | BeginCall
  | Literal of string
  | Int of int
  | Name of string
  | BeginBlock
  | Comparison of TplAst.comparison
  | And
  | Or
  | Not
  | OpenBracket
  | CloseBracket
  | OpenParen
  | CloseParen
  | EndEcho
  | EndI18n
  | EndCall
  | EndSub
  | Dot
  | Eof

(** Creates a new lexer function (called repeatedly on a lexing
    buffer and returns a new token each time) *)
val make : unit -> Lexing.lexbuf -> token
